name: pet_adoption_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Font awesome icons
  font_awesome_flutter: ^10.1.0

  #Firebase
  cloud_firestore: ^3.1.12
  firebase_auth: ^3.3.5
  firebase_core: ^1.0.3
  #Validate email_auth
  email_validator: ^2.0.1
  #Image picker:
  image_picker: ^0.8.5
  #Store image
  path_provider: ^2.0.9
  #Http
  http: ^0.13.4
  #Youtube
  youtube_player_flutter: ^8.1.0
  #Hive
  hive: ^2.2.1
  hive_generator: ^1.1.3
  hive_flutter: ^1.1.0
  #Internet connection checker
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

  #Hive
  build_runner: ^2.1.11

flutter:


  uses-material-design: true
  assets:
    - images/

